// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class card_define : System.ICloneable
    {
        
        public int cardID;
        
        public int skillNormal1;
        
        public int skillNormal2;
        
        public int skillNormal3;
        
        public int skillNormal4;
        
        public int skillSpecial1;
        
        public int skillSpecial2;
        
        public int skillSpecial3;
        
        public int skillSpecial4;
        
        public int decisionType1;
        
        public int decisionType2;
        
        public int decisionType3;
        
        public int decisionType4;
        
        public int otherSkill1;
        
        public int otherSkill2;
        
        public int otherSkill3;
        
        public int otherSkill4;
        
        public float MoveSpeed;
        
        public float RollDis;
        
        public float RollTime;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablecard_define : XWorld.DataConfig.TableBase
    {
        
        public List<card_define> m_configList = new List<card_define>();
        
        public void LoadData(XWorld.DataConfig.card_define codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 20;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public card_define GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                card_define data = new card_define();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.cardID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillNormal1 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillNormal2 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillNormal3 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillNormal4 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillSpecial1 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillSpecial2 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillSpecial3 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.skillSpecial4 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.decisionType1 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.decisionType2 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.decisionType3 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.decisionType4 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.otherSkill1 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.otherSkill2 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.otherSkill3 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.otherSkill4 = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.MoveSpeed = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.RollDis = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.RollTime = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
