// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class commonaudio : System.ICloneable
    {
        
        public int audioid;
        
        public string des;
        
        public int isLoop;
        
        public string path;
        
        public float lifetime;
        
        public float fadeinTime;
        
        public float fadeoutTime;
        
        public int maxCount;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablecommonaudio : XWorld.DataConfig.TableBase
    {
        
        public List<commonaudio> m_configList = new List<commonaudio>();
        
        public void LoadData(XWorld.DataConfig.commonaudio codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 8;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public commonaudio GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                commonaudio data = new commonaudio();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.audioid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.des = (subValues[j]);
                    j = j + 1;
                    data.isLoop = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.path = (subValues[j]);
                    j = j + 1;
                    data.lifetime = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.fadeinTime = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.fadeoutTime = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.maxCount = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
