// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class content_monster_define : System.ICloneable
    {
        
        public int ID;
        
        public string Key;
        
        public string Pos;
        
        public string navPos;
        
        public string rotPos;
        
        public string scalePos;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablecontent_monster_define : XWorld.DataConfig.TableBase
    {
        
        public List<content_monster_define> m_configList = new List<content_monster_define>();
        
        public void LoadData(XWorld.DataConfig.content_monster_define codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 6;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public content_monster_define GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                content_monster_define data = new content_monster_define();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.ID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.Key = (subValues[j]);
                    j = j + 1;
                    data.Pos = (subValues[j]);
                    j = j + 1;
                    data.navPos = (subValues[j]);
                    j = j + 1;
                    data.rotPos = (subValues[j]);
                    j = j + 1;
                    data.scalePos = (subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
