// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class ui_config : System.ICloneable
    {
        
        public string uiTag;
        
        public string uiDesc;
        
        public int uiLevel;
        
        public string PrefabName;
        
        public int uiType;
        
        public int createByProdure;
        
        public int clearByChangeScene;
        
        public int clearByProcedure;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tableui_config : XWorld.DataConfig.TableBase
    {
        
        public List<ui_config> m_configList = new List<ui_config>();
        
        public void LoadData(XWorld.DataConfig.ui_config codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 8;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public ui_config GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                ui_config data = new ui_config();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.uiTag = (subValues[j]);
                    j = j + 1;
                    data.uiDesc = (subValues[j]);
                    j = j + 1;
                    data.uiLevel = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.PrefabName = (subValues[j]);
                    j = j + 1;
                    data.uiType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.createByProdure = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.clearByChangeScene = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.clearByProcedure = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
