// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class CreditType : System.ICloneable
    {
        
        public short typeid;
        
        public string typename;
        
        public short defaultlevel;
        
        public int playertype;
        
        public int pktype;
        
        public int IgnoreAmityDamage;
        
        public int ShowNameID;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class TableCreditType : XWorld.DataConfig.TableBase
    {
        
        public List<CreditType> m_configList = new List<CreditType>();
        
        public void LoadData(XWorld.DataConfig.CreditType codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 7;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public CreditType GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                CreditType data = new CreditType();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.typeid = ClientConfigManager.ToInt16(subValues[j]);
                    j = j + 1;
                    data.typename = (subValues[j]);
                    j = j + 1;
                    data.defaultlevel = ClientConfigManager.ToInt16(subValues[j]);
                    j = j + 1;
                    data.playertype = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.pktype = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.IgnoreAmityDamage = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.ShowNameID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
