// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class item_equipdata : System.ICloneable
    {
        
        public int itemid;
        
        public int reqlevel;
        
        public int suitid;
        
        public int exattrgroupid;
        
        public int attributegroupid;
        
        public int colorindex;
        
        public int modelid;
        
        public int modelid_F;
        
        public int durabilitymax;
        
        public int lingqi;
        
        public float speedpercent;
        
        public int fixtemplateid;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tableitem_equipdata : XWorld.DataConfig.TableBase
    {
        
        public List<item_equipdata> m_configList = new List<item_equipdata>();
        
        public void LoadData(XWorld.DataConfig.item_equipdata codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 12;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public item_equipdata GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                item_equipdata data = new item_equipdata();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.itemid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.reqlevel = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.suitid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.exattrgroupid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.attributegroupid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.colorindex = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.modelid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.modelid_F = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.durabilitymax = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.lingqi = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.speedpercent = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.fixtemplateid = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
