// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class modelresanimation : System.ICloneable
    {
        
        public int AnimationID;
        
        public string AnimName;
        
        public int IsSelfRestart;
        
        public int Motion;
        
        public int Layer;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablemodelresanimation : XWorld.DataConfig.TableBase
    {
        
        public List<modelresanimation> m_configList = new List<modelresanimation>();
        
        public void LoadData(XWorld.DataConfig.modelresanimation codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 5;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public modelresanimation GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                modelresanimation data = new modelresanimation();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.AnimationID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AnimName = (subValues[j]);
                    j = j + 1;
                    data.IsSelfRestart = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.Motion = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.Layer = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
