// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class modelresdefine : System.ICloneable
    {
        
        public int ModelID;
        
        public string ModelName;
        
        public string AnimationSetName;
        
        public float BillboardHight;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablemodelresdefine : XWorld.DataConfig.TableBase
    {
        
        public List<modelresdefine> m_configList = new List<modelresdefine>();
        
        public void LoadData(XWorld.DataConfig.modelresdefine codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 4;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public modelresdefine GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                modelresdefine data = new modelresdefine();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.ModelID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.ModelName = (subValues[j]);
                    j = j + 1;
                    data.AnimationSetName = (subValues[j]);
                    j = j + 1;
                    data.BillboardHight = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
