// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class modifydata : System.ICloneable
    {
        
        public int Type;
        
        public int DataID;
        
        public int ModifyID;
        
        public string ValueName;
        
        public int IValue;
        
        public float FValue;
        
        public float Precent;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablemodifydata : XWorld.DataConfig.TableBase
    {
        
        public List<modifydata> m_configList = new List<modifydata>();
        
        public void LoadData(XWorld.DataConfig.modifydata codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 7;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public modifydata GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                modifydata data = new modifydata();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.Type = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.DataID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.ModifyID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.ValueName = (subValues[j]);
                    j = j + 1;
                    data.IValue = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.FValue = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    data.Precent = ClientConfigManager.ToSingle(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
