// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class PreSkillData : System.ICloneable
    {
        
        public int Idx;
        
        public int AreaType;
        
        public int AreaEffectID;
        
        public int FollowType;
        
        public int RangeType;
        
        public int RangeEffectID;
        
        public int CameraEffectID;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class TablePreSkillData : XWorld.DataConfig.TableBase
    {
        
        public List<PreSkillData> m_configList = new List<PreSkillData>();
        
        public void LoadData(XWorld.DataConfig.PreSkillData codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 7;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public PreSkillData GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                PreSkillData data = new PreSkillData();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.Idx = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AreaType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AreaEffectID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.FollowType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.RangeType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.RangeEffectID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.CameraEffectID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
