// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class quest_def : System.ICloneable
    {
        
        public int QuestID;
        
        public int QuestTitleID;
        
        public int AcceptNpc;
        
        public int AcceptDlg;
        
        public int EventID;
        
        public string NextQuest;
        
        public int Period;
        
        public int AcceptCount;
        
        public int FinishCount;
        
        public int AcceptCheck;
        
        public int CanSeeCheck;
        
        public int QuestType;
        
        public int NameShowType;
        
        public int TeamFlag;
        
        public int QuestFlag;
        
        public int DescontentID;
        
        public string QuestActionLua;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class Tablequest_def : XWorld.DataConfig.TableBase
    {
        
        public List<quest_def> m_configList = new List<quest_def>();
        
        public void LoadData(XWorld.DataConfig.quest_def codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 17;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public quest_def GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                quest_def data = new quest_def();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.QuestID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.QuestTitleID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AcceptNpc = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AcceptDlg = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.EventID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.NextQuest = (subValues[j]);
                    j = j + 1;
                    data.Period = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AcceptCount = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.FinishCount = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AcceptCheck = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.CanSeeCheck = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.QuestType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.NameShowType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.TeamFlag = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.QuestFlag = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.DescontentID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.QuestActionLua = (subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
