// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class Quest_Gift : System.ICloneable
    {
        
        public int EventID;
        
        public string GiftValueType;
        
        public string GiftValue;
        
        public string GiftItemID;
        
        public string GiftItemCount;
        
        public string IsBind;
        
        public string GiftLua;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class TableQuest_Gift : XWorld.DataConfig.TableBase
    {
        
        public List<Quest_Gift> m_configList = new List<Quest_Gift>();
        
        public void LoadData(XWorld.DataConfig.Quest_Gift codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 7;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public Quest_Gift GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                Quest_Gift data = new Quest_Gift();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.EventID = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.GiftValueType = (subValues[j]);
                    j = j + 1;
                    data.GiftValue = (subValues[j]);
                    j = j + 1;
                    data.GiftItemID = (subValues[j]);
                    j = j + 1;
                    data.GiftItemCount = (subValues[j]);
                    j = j + 1;
                    data.IsBind = (subValues[j]);
                    j = j + 1;
                    data.GiftLua = (subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
