// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public class SkillAimAssist : System.ICloneable
    {
        
        public int Idx;
        
        public string Des;
        
        public int AimAssistType;
        
        public int AimAssistRule;
        
        public int AimAssistEffect;
        
        public object Clone()
        {
            return this.MemberwiseClone();;
        }
    }
    
    public class TableSkillAimAssist : XWorld.DataConfig.TableBase
    {
        
        public List<SkillAimAssist> m_configList = new List<SkillAimAssist>();
        
        public void LoadData(XWorld.DataConfig.SkillAimAssist codeValue)
        {
            m_configList.Add(codeValue);
        }
        
        public int GetRowCount()
        {
            return 5;
        }
        
        public int GetDataCount()
        {
            if (m_configList == null)
            {
                return 0;
            }
            return m_configList.Count;
        }
        
        public SkillAimAssist GetData(int rowIdx)
        {
            if (m_configList != null && rowIdx >= 0 && rowIdx < m_configList.Count)
            {
                return m_configList[rowIdx];
            }
            return null;
        }
        
        public override void LoadData(string content)
        {
            string[] values = content.Split("\r"[0]);
            for (int i = 2; (i < values.Length); i = (i + 1))
            {
                SkillAimAssist data = new SkillAimAssist();
                int j = 0;
                string[] subValues = values[i].TrimStart('\n').Split(ClientConfigManager.CMD_STRING, StringSplitOptions.None);
                if (subValues != null && subValues.Length == GetRowCount())
                {
                    data.Idx = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.Des = (subValues[j]);
                    j = j + 1;
                    data.AimAssistType = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AimAssistRule = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    data.AimAssistEffect = ClientConfigManager.ToInt32(subValues[j]);
                    j = j + 1;
                    m_configList.Add(data);
                }
            }
        }
    }
}
