// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XWorld.DataConfig
{
    using UnityEngine;
    using System.Collections.Generic;
    using System;
    
    
    public partial class ClientConfigManager : MonoBehaviour
    {
        
        public static TableAICheckCondition m_tableAICheckCondition;
        
        public static Tablebuffdata m_tablebuffdata;
        
        public static Tablecddefine m_tablecddefine;
        
        public static TableClientCheckCondition m_tableClientCheckCondition;
        
        public static Tablecommoneffects m_tablecommoneffects;
        
        public static TableCreditRelation m_tableCreditRelation;
        
        public static TableCreditType m_tableCreditType;
        
        public static TableDebugString m_tableDebugString;
        
        public static Tabledialogdata m_tabledialogdata;
        
        public static Tabledialoggroup m_tabledialoggroup;
        
        public static TableDialogString m_tableDialogString;
        
        public static Tableeventtable m_tableeventtable;
        
        public static TableFSMGameFlagCheckCondition m_tableFSMGameFlagCheckCondition;
        
        public static Tableitem_equipdata m_tableitem_equipdata;
        
        public static Tableitem_itemdata m_tableitem_itemdata;
        
        public static TableLocationDesStr m_tableLocationDesStr;
        
        public static TableMessageString m_tableMessageString;
        
        public static Tablemissilecurve m_tablemissilecurve;
        
        public static Tablemodelresanimation m_tablemodelresanimation;
        
        public static Tablemodelresdefine m_tablemodelresdefine;
        
        public static Tablemodifydata m_tablemodifydata;
        
        public static Tablenodecommoncheckcondition m_tablenodecommoncheckcondition;
        
        public static Tablenodecommoncheckgroup m_tablenodecommoncheckgroup;
        
        public static TableNoticeString m_tableNoticeString;
        
        public static TableOtherString m_tableOtherString;
        
        public static TablePreSkillData m_tablePreSkillData;
        
        public static Tablequest_def m_tablequest_def;
        
        public static TableQuest_Gift m_tableQuest_Gift;
        
        public static Tablescenedefine m_tablescenedefine;
        
        public static TableSkillAimAssist m_tableSkillAimAssist;
        
        public static TableSkillCheckCondition m_tableSkillCheckCondition;
        
        public static Tableskilldata m_tableskilldata;
        
        public static TableUIString m_tableUIString;
        
        public static Tablecard_define m_tablecard_define;
        
        public static Tableclient_config_define m_tableclient_config_define;
        
        public static Tableclient_skill_data m_tableclient_skill_data;
        
        public static Tablecommonaudio m_tablecommonaudio;
        
        public static Tablecontent_monster_define m_tablecontent_monster_define;
        
        public static Tablecontent_trigger_define m_tablecontent_trigger_define;
        
        public static Tablescene_trigger_define m_tablescene_trigger_define;
        
        public static Tableshow_room_config m_tableshow_room_config;
        
        public static TableSkillGroup m_tableSkillGroup;
        
        public static Tableskill_set_define m_tableskill_set_define;
        
        public static Tabletransition_tips m_tabletransition_tips;
        
        public static Tableui_config m_tableui_config;
    }
}
